/**
 * @description
 * This file defines the TypeScript interface for the Trade Parameter Template.
 * It corresponds to the `TradeTemplate` model defined in the Prisma schema.
 *
 * @dependencies
 * - None
 *
 * @notes
 * - This type is used for managing trade templates, likely via the settings UI
 * and interacting with the `template-actions.ts` Server Actions.
 */

/**
 * Represents a saved Trade Parameter Template.
 * Users can create, save, and apply these templates when staging a trade.
 *
 * @property {string} id - Unique identifier for the template (generated by Prisma).
 * @property {string} name - User-defined name for the template (must be unique).
 * @property {number} size - The trade size (e.g., in BTC units) saved in the template.
 * @property {number} leverage - The leverage value saved in the template.
 * @property {Date} createdAt - Timestamp when the template was created (managed by Prisma).
 * @property {Date} updatedAt - Timestamp when the template was last updated (managed by Prisma).
 */
export interface TradeTemplate {
    id: string;
    name: string;
    size: number;
    leverage: number;
    createdAt: Date;
    updatedAt: Date;
  }